# Assignment 4 - Clustering

Loading Data

In [1]:
import config, etl
data = etl.read_csvfile(config.DATAFILE)

Data Cleaning

In [2]:
# Data Cleaning
data = etl.replace_dates_with_datetime(data, config.TO_DATE)
data = etl.replace_missing_with_mode(data, data, config.MISSING)

In [3]:
data = data[config.FEATURES]
data.head()

,school_state,school_metro,school_charter,school_magnet,primary_focus_subject,primary_focus_area,secondary_focus_subject,secondary_focus_area,resource_type,poverty_level,grade_level,total_price_including_optional_support,students_reached,eligible_double_your_impact_match,school_latitude,school_longitude,total_price_including_optional_support,students_reached
0,IL,urban,f,f,Mathematics,Math & Science,Visual Arts,Music & The Arts,Supplies,highest poverty,Grades PreK-2,1498.61,31.0,f,41.807654,-87.673257,1498.61,31.0
1,CA,urban,f,f,Civics & Government,History & Civics,Literature & Writing,Literacy & Language,Books,highest poverty,Grades 3-5,282.47,28.0,t,34.296596,-119.296596,282.47,28.0
2,CA,urban,f,f,Literacy,Literacy & Language,Social Sciences,History & Civics,Technology,high poverty,Grades 3-5,1012.38,56.0,f,34.078625,-118.257834,1012.38,56.0
3,NY,urban,f,t,Literacy,Literacy & Language,Literacy,Literacy & Language,Books,high poverty,Grades PreK-2,175.33,23.0,f,40.687286,-73.988217,175.33,23.0
4,NY,suburban,f,f,Literacy,Literacy & Language,Literature & Writing,Literacy & Language,Technology,high poverty,Grades PreK-2,3591.11,150.0,f,40.793018,-73.205635,3591.11,150.0

In [4]:
# Create Dummies
for cat in config.CATEGORICAL:
    data = etl.create_dummies(data, cat)

In [5]:
# Scaling Continuous Var
#from sklearn.preprocessing import MinMaxScaler

#scaler = MinMaxScaler()
#for c in config.CONTINUOUS:
#    data = scaler.fit_transform(data[c].values.reshape(-1, 1))

Build Clusters

In [9]:
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import pandas as pd

clusters = [2]
for n in clusters:
    kmeans = KMeans(n_clusters=n, random_state=0).fit(data)
    data['pred_label'] = pd.Series(kmeans.labels_)
    print(data.groupby('pred_label').mean())

            school_latitude  school_longitude  school_state_AL  \
pred_label
0                 36.827488        -95.861193         0.007539
1                 36.027980        -88.463900         0.000000

            school_state_AR  school_state_AZ  school_state_CA  \
pred_label
0                  0.011133         0.018864         0.233897
1                  0.000000         0.031250         0.093750

            school_state_CO  school_state_CT  school_state_DC  \
pred_label
0                  0.012261         0.011085         0.006195
1                  0.000000         0.031250         0.062500

            school_state_DE  ...  poverty_level_low poverty  \
pred_label                   ...
0                  0.003418  ...                    0.03039
1                  0.000000  ...                    0.00000

            poverty_level_moderate poverty  grade_level_Grades 6-8  \
pred_label
0                                 0.152572                0.171853
1                                 0.093750                0.218750

            grade_level_Grades 9-12  grade_level_Grades PreK-2  \
pred_label
0                          0.132131                   0.382003
1                          0.406250                   0.125000

            total_price_including_optional_support  \
pred_label
0                                       642.842453
1                                     44264.772812

            total_price_including_optional_support  students_reached  \
pred_label
0                                       642.842453         95.132131
1                                     44264.772812       1190.125000

            students_reached  eligible_double_your_impact_match_t
pred_label
0                  95.132131                             0.296837
1                1190.125000                             0.031250

[2 rows x 136 columns]